// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using RegistrationPage.Data;

#nullable disable

namespace RegistrationPage.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20241230130132_CountryDistrictUpozilaNew")]
    partial class CountryDistrictUpozilaNew
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("RegistrationPage.Models.Entities.Address", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CreateAccountId")
                        .HasColumnType("int");

                    b.Property<int>("DistrictId")
                        .HasColumnType("int");

                    b.Property<string>("PostOffice")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UpozilaId")
                        .HasColumnType("int");

                    b.Property<string>("Village")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("CreateAccountId")
                        .IsUnique();

                    b.HasIndex("DistrictId")
                        .IsUnique();

                    b.HasIndex("UpozilaId")
                        .IsUnique();

                    b.ToTable("Addresses");
                });

            modelBuilder.Entity("RegistrationPage.Models.Entities.Country", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Countries");
                });

            modelBuilder.Entity("RegistrationPage.Models.Entities.CreateAccount", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Age")
                        .HasColumnType("int");

                    b.Property<int>("CountryId")
                        .HasColumnType("int");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Gender")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MobileNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Skill")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CountryId")
                        .IsUnique();

                    b.ToTable("CreateAccounts");
                });

            modelBuilder.Entity("RegistrationPage.Models.Entities.District", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CountryId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("CountryId");

                    b.ToTable("Districts");
                });

            modelBuilder.Entity("RegistrationPage.Models.Entities.EducationalQualification", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Board")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("CreateAccountId")
                        .HasColumnType("int");

                    b.Property<string>("EducationalStage")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MajorSubject")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NameOfEducationalInstitution")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateOnly>("YearOfPassing")
                        .HasColumnType("date");

                    b.HasKey("Id");

                    b.HasIndex("CreateAccountId");

                    b.ToTable("EducationalQualifications");
                });

            modelBuilder.Entity("RegistrationPage.Models.Entities.Upozila", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("DistrictId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("DistrictId");

                    b.ToTable("Upozilas");
                });

            modelBuilder.Entity("RegistrationPage.Models.Entities.Address", b =>
                {
                    b.HasOne("RegistrationPage.Models.Entities.CreateAccount", "CreateAccount")
                        .WithOne("Address")
                        .HasForeignKey("RegistrationPage.Models.Entities.Address", "CreateAccountId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("RegistrationPage.Models.Entities.District", "District")
                        .WithOne("Address")
                        .HasForeignKey("RegistrationPage.Models.Entities.Address", "DistrictId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("RegistrationPage.Models.Entities.Upozila", "Upozila")
                        .WithOne("Address")
                        .HasForeignKey("RegistrationPage.Models.Entities.Address", "UpozilaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CreateAccount");

                    b.Navigation("District");

                    b.Navigation("Upozila");
                });

            modelBuilder.Entity("RegistrationPage.Models.Entities.CreateAccount", b =>
                {
                    b.HasOne("RegistrationPage.Models.Entities.Country", "Country")
                        .WithOne("CreateAccount")
                        .HasForeignKey("RegistrationPage.Models.Entities.CreateAccount", "CountryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Country");
                });

            modelBuilder.Entity("RegistrationPage.Models.Entities.District", b =>
                {
                    b.HasOne("RegistrationPage.Models.Entities.Country", "Country")
                        .WithMany("Districts")
                        .HasForeignKey("CountryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Country");
                });

            modelBuilder.Entity("RegistrationPage.Models.Entities.EducationalQualification", b =>
                {
                    b.HasOne("RegistrationPage.Models.Entities.CreateAccount", "CreateAccount")
                        .WithMany("EducationalQualifications")
                        .HasForeignKey("CreateAccountId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CreateAccount");
                });

            modelBuilder.Entity("RegistrationPage.Models.Entities.Upozila", b =>
                {
                    b.HasOne("RegistrationPage.Models.Entities.District", "District")
                        .WithMany("Upozilas")
                        .HasForeignKey("DistrictId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("District");
                });

            modelBuilder.Entity("RegistrationPage.Models.Entities.Country", b =>
                {
                    b.Navigation("CreateAccount")
                        .IsRequired();

                    b.Navigation("Districts");
                });

            modelBuilder.Entity("RegistrationPage.Models.Entities.CreateAccount", b =>
                {
                    b.Navigation("Address")
                        .IsRequired();

                    b.Navigation("EducationalQualifications");
                });

            modelBuilder.Entity("RegistrationPage.Models.Entities.District", b =>
                {
                    b.Navigation("Address")
                        .IsRequired();

                    b.Navigation("Upozilas");
                });

            modelBuilder.Entity("RegistrationPage.Models.Entities.Upozila", b =>
                {
                    b.Navigation("Address")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
